### ISSUE TITLE
Where the train_Y.csv

### ISSUE THREAD

**Issue by Moon-creat** [ajaychawda58/UADAD#1]
![image](https://github.com/ajaychawda58/UADAD/assets/129244270/bffd75c3-63d1-4636-9a0f-2a503ec1a005)

**Comment by ajaychawda58** [comment]
Please use the labels from /data/vehicle_claims_labeled.csv . The feature `label` must be used for train_Y.csv. It also depends on your train test split how the train_Y.csv looks like.
